exclude:
  - README.md
  - requirements.txt
  - scripts/
  - tests/
  - LICENSE

plugins:
  - jekyll-gfm-admonitions
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-octicons
  - jekyll-github-metadata
  
markdown: kramdown
kramdown:
  input: GFM

sass:
  sourcemap: development

remote_theme: jekyll/minima

minima:
  skin: auto
  show_excerpts: true
  hide_site_feed_link: true

title: Library + Portfolio

##################################
# Start of landing page settings
##################################

intro:
  switch: true
  text: Course notes, projects, and essays.

repo_grid:
  switch: true
  repo_list:
    - tech-lib
    - bus-lib
    - open-banking-lakehouse
    - lib-port.github.io
    - agentless-DaC
    - backtest
    - ansible-linux-audit
    - pricing-function-mapper

external_blog:
  switch: false
  feed_url:
  archive_url:
  post_limit: 7

################################
# End of landing page settings
################################

description: A blog and portfolio site focusing on the intersection of technology, social sciences, and humanities.
